### ISSUE TITLE
Strapi 5 compatibility

### ISSUE THREAD

**Issue by cayblood** [ijsto/strapi-provider-email-postmark#11]
I'm wondering if this should also work with Strapi 5, and if anyone has tested it already. Thanks!

**Comment by cayblood** [comment]
I was able to install this successfully on strapi5. There may be a few npm packages that could be upgraded, but it worked.

**Comment by laurenskling** [comment]
@ScottAgirs maybe we can do a Strapi 5 version? Up @strapi/utils etc.
