### ISSUE TITLE
forgot-password not working 

### ISSUE THREAD

**Issue by laurenskling** [ijsto/strapi-provider-email-postmark#7]
I guess we both never spotted this:

```
debug POST /admin/forgot-password (7 ms) 204
error ApiInputError: A 'TemplateModel' may not be specified when sending through the '/email' endpoint. Please use the '/email/withTemplate' endpoint instead.
```

Will do some research a.s.a.p.

**Comment by ScottAgirs** [comment]
Yikes. Yeah, that has slipped by nice catch!

I'm currently tied up with another project, and I'm not using this API in my apps, so if you have time to take a look at this - that's awesome!! 🙌🏼

**Comment by laurenskling** [comment]
Our latest change https://github.com/ijsto/strapi-provider-email-postmark/blob/master/lib/index.js#L49 makes it so that variables is always set, even tho it might not be a templated mail. I guess we will have to put this in the if statement checking if we are sending a template

**Comment by ScottAgirs** [comment]
@laurenskling thanks for the PR, 3.5.1 has been published to NPM.

**Comment by laurenskling** [comment]
Thanks so much mate
